spring:
  cloud:
    stream:
      default-binder: local_solace
      bindings:
        input:
          destination: TWEETS.Q
          group: DYNAMICFEATURES
      binders:
        local_solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: default
                clientPassword: default
                connectRetries: 3
                connectRetriesPerHost: 0
                reconnectRetries: 3
      solace:
        bindings:
          input:
            consumer:
              queueAdditionalSubscriptions: tweets/stream
logging:
  level:
    root: INFO
    com.solacesystems.jcsmp: INFO
    org.springframework: INFO
    
server:
  port: 8097
